/* Procedures Generada desde Cix-PHP - by power @armandoaepp */
DELIMITER ;;
CREATE PROCEDURE usp_set_cellocator( idrastreo int(11),RMUId varchar(10),CellDateTime datetime,GPSX int(11),GPSY int(11),GPSDateTime datetime,Speed int(11),Direction int(11),NumOfSat int(11),LocQuality int(11),EngineOn int(11),ExtInputA int(11),ExtInputB int(11),ExtInputC int(11),ExtInputD int(11),ExtInputE int(11),ExtInputF int(11),VersionNum varchar(25),IP varchar(15),InputVoltage int(11),BackBatVoltage int(11),GPSPDOP smallint(6),GPSHEIGHT int(11),NetworkTypeId smallint(6),InsertDate datetime,UTCTime datetime,DriverId mediumtext,TxReasonId int(11),AlertReason int(11),Hibernation int(11),HRNetwork int(11),MileCounter int(11),GPSMode1 int(11),GPSMode2 int(11),OutputA int(11),OutputB int(11),OutputC int(11),OutputD int(11),OptionalInput int(11),GPSCommStatus int(11),RawData varchar(2000),PLMN int(11),SN int(11),MessageType int(11),MsgProtocol smallint(6),TripId int(11),ManeuverId int(11),ManeuverUsage smallint(6),AccidentBuffer int(11),ItemId mediumtext )
BEGIN
	INSERT INTO  cellocator(
		cellocator.idrastreo,
		cellocator.RMUId,
		cellocator.CellDateTime,
		cellocator.GPSX,
		cellocator.GPSY,
		cellocator.GPSDateTime,
		cellocator.Speed,
		cellocator.Direction,
		cellocator.NumOfSat,
		cellocator.LocQuality,
		cellocator.EngineOn,
		cellocator.ExtInputA,
		cellocator.ExtInputB,
		cellocator.ExtInputC,
		cellocator.ExtInputD,
		cellocator.ExtInputE,
		cellocator.ExtInputF,
		cellocator.VersionNum,
		cellocator.IP,
		cellocator.InputVoltage,
		cellocator.BackBatVoltage,
		cellocator.GPSPDOP,
		cellocator.GPSHEIGHT,
		cellocator.NetworkTypeId,
		cellocator.InsertDate,
		cellocator.UTCTime,
		cellocator.DriverId,
		cellocator.TxReasonId,
		cellocator.AlertReason,
		cellocator.Hibernation,
		cellocator.HRNetwork,
		cellocator.MileCounter,
		cellocator.GPSMode1,
		cellocator.GPSMode2,
		cellocator.OutputA,
		cellocator.OutputB,
		cellocator.OutputC,
		cellocator.OutputD,
		cellocator.OptionalInput,
		cellocator.GPSCommStatus,
		cellocator.RawData,
		cellocator.PLMN,
		cellocator.SN,
		cellocator.MessageType,
		cellocator.MsgProtocol,
		cellocator.TripId,
		cellocator.ManeuverId,
		cellocator.ManeuverUsage,
		cellocator.AccidentBuffer,
		cellocator.ItemId
	)
	VALUES(
		null,
		RMUId,
		CellDateTime,
		GPSX,
		GPSY,
		GPSDateTime,
		Speed,
		Direction,
		NumOfSat,
		LocQuality,
		EngineOn,
		ExtInputA,
		ExtInputB,
		ExtInputC,
		ExtInputD,
		ExtInputE,
		ExtInputF,
		VersionNum,
		IP,
		InputVoltage,
		BackBatVoltage,
		GPSPDOP,
		GPSHEIGHT,
		NetworkTypeId,
		InsertDate,
		UTCTime,
		DriverId,
		TxReasonId,
		AlertReason,
		Hibernation,
		HRNetwork,
		MileCounter,
		GPSMode1,
		GPSMode2,
		OutputA,
		OutputB,
		OutputC,
		OutputD,
		OptionalInput,
		GPSCommStatus,
		RawData,
		PLMN,
		SN,
		MessageType,
		MsgProtocol,
		TripId,
		ManeuverId,
		ManeuverUsage,
		AccidentBuffer,
		ItemId
	);
END;;
DELIMITER ;;

DELIMITER ;;
CREATE PROCEDURE usp_upd_cellocator( idrastreo int(11),RMUId varchar(10),CellDateTime datetime,GPSX int(11),GPSY int(11),GPSDateTime datetime,Speed int(11),Direction int(11),NumOfSat int(11),LocQuality int(11),EngineOn int(11),ExtInputA int(11),ExtInputB int(11),ExtInputC int(11),ExtInputD int(11),ExtInputE int(11),ExtInputF int(11),VersionNum varchar(25),IP varchar(15),InputVoltage int(11),BackBatVoltage int(11),GPSPDOP smallint(6),GPSHEIGHT int(11),NetworkTypeId smallint(6),InsertDate datetime,UTCTime datetime,DriverId mediumtext,TxReasonId int(11),AlertReason int(11),Hibernation int(11),HRNetwork int(11),MileCounter int(11),GPSMode1 int(11),GPSMode2 int(11),OutputA int(11),OutputB int(11),OutputC int(11),OutputD int(11),OptionalInput int(11),GPSCommStatus int(11),RawData varchar(2000),PLMN int(11),SN int(11),MessageType int(11),MsgProtocol smallint(6),TripId int(11),ManeuverId int(11),ManeuverUsage smallint(6),AccidentBuffer int(11),ItemId mediumtext )
BEGIN
	UPDATE cellocator SET
		cellocator.idrastreo = idrastreo,
		cellocator.RMUId = RMUId,
		cellocator.CellDateTime = CellDateTime,
		cellocator.GPSX = GPSX,
		cellocator.GPSY = GPSY,
		cellocator.GPSDateTime = GPSDateTime,
		cellocator.Speed = Speed,
		cellocator.Direction = Direction,
		cellocator.NumOfSat = NumOfSat,
		cellocator.LocQuality = LocQuality,
		cellocator.EngineOn = EngineOn,
		cellocator.ExtInputA = ExtInputA,
		cellocator.ExtInputB = ExtInputB,
		cellocator.ExtInputC = ExtInputC,
		cellocator.ExtInputD = ExtInputD,
		cellocator.ExtInputE = ExtInputE,
		cellocator.ExtInputF = ExtInputF,
		cellocator.VersionNum = VersionNum,
		cellocator.IP = IP,
		cellocator.InputVoltage = InputVoltage,
		cellocator.BackBatVoltage = BackBatVoltage,
		cellocator.GPSPDOP = GPSPDOP,
		cellocator.GPSHEIGHT = GPSHEIGHT,
		cellocator.NetworkTypeId = NetworkTypeId,
		cellocator.InsertDate = InsertDate,
		cellocator.UTCTime = UTCTime,
		cellocator.DriverId = DriverId,
		cellocator.TxReasonId = TxReasonId,
		cellocator.AlertReason = AlertReason,
		cellocator.Hibernation = Hibernation,
		cellocator.HRNetwork = HRNetwork,
		cellocator.MileCounter = MileCounter,
		cellocator.GPSMode1 = GPSMode1,
		cellocator.GPSMode2 = GPSMode2,
		cellocator.OutputA = OutputA,
		cellocator.OutputB = OutputB,
		cellocator.OutputC = OutputC,
		cellocator.OutputD = OutputD,
		cellocator.OptionalInput = OptionalInput,
		cellocator.GPSCommStatus = GPSCommStatus,
		cellocator.RawData = RawData,
		cellocator.PLMN = PLMN,
		cellocator.SN = SN,
		cellocator.MessageType = MessageType,
		cellocator.MsgProtocol = MsgProtocol,
		cellocator.TripId = TripId,
		cellocator.ManeuverId = ManeuverId,
		cellocator.ManeuverUsage = ManeuverUsage,
		cellocator.AccidentBuffer = AccidentBuffer,
		cellocator.ItemId = ItemId
	WHERE cellocator.idrastreo = idrastreo;
END;;
DELIMITER ;;

DELIMITER ;;
CREATE PROCEDURE usp_upd_cellocator_estado(idrastreo int(11),ItemId mediumtext)
BEGIN
	UPDATE cellocator SET
		cellocator.ItemId = ItemId
	WHERE cellocator.idrastreo = idrastreo;
END;;
DELIMITER ;;

DELIMITER ;;
CREATE PROCEDURE usp_get_cellocator_by_idrastreo(idrastreo int(11))
BEGIN
	SELECT
		cellocator.idrastreo,
		cellocator.RMUId,
		cellocator.CellDateTime,
		cellocator.GPSX,
		cellocator.GPSY,
		cellocator.GPSDateTime,
		cellocator.Speed,
		cellocator.Direction,
		cellocator.NumOfSat,
		cellocator.LocQuality,
		cellocator.EngineOn,
		cellocator.ExtInputA,
		cellocator.ExtInputB,
		cellocator.ExtInputC,
		cellocator.ExtInputD,
		cellocator.ExtInputE,
		cellocator.ExtInputF,
		cellocator.VersionNum,
		cellocator.IP,
		cellocator.InputVoltage,
		cellocator.BackBatVoltage,
		cellocator.GPSPDOP,
		cellocator.GPSHEIGHT,
		cellocator.NetworkTypeId,
		cellocator.InsertDate,
		cellocator.UTCTime,
		cellocator.DriverId,
		cellocator.TxReasonId,
		cellocator.AlertReason,
		cellocator.Hibernation,
		cellocator.HRNetwork,
		cellocator.MileCounter,
		cellocator.GPSMode1,
		cellocator.GPSMode2,
		cellocator.OutputA,
		cellocator.OutputB,
		cellocator.OutputC,
		cellocator.OutputD,
		cellocator.OptionalInput,
		cellocator.GPSCommStatus,
		cellocator.RawData,
		cellocator.PLMN,
		cellocator.SN,
		cellocator.MessageType,
		cellocator.MsgProtocol,
		cellocator.TripId,
		cellocator.ManeuverId,
		cellocator.ManeuverUsage,
		cellocator.AccidentBuffer,
		cellocator.ItemId
	FROM cellocator
	WHERE  cellocator.idrastreo = idrastreo;
END;;
DELIMITER ;;

DELIMITER ;;
CREATE PROCEDURE usp_get_cellocator()
BEGIN
	SELECT
		cellocator.idrastreo,
		cellocator.RMUId,
		cellocator.CellDateTime,
		cellocator.GPSX,
		cellocator.GPSY,
		cellocator.GPSDateTime,
		cellocator.Speed,
		cellocator.Direction,
		cellocator.NumOfSat,
		cellocator.LocQuality,
		cellocator.EngineOn,
		cellocator.ExtInputA,
		cellocator.ExtInputB,
		cellocator.ExtInputC,
		cellocator.ExtInputD,
		cellocator.ExtInputE,
		cellocator.ExtInputF,
		cellocator.VersionNum,
		cellocator.IP,
		cellocator.InputVoltage,
		cellocator.BackBatVoltage,
		cellocator.GPSPDOP,
		cellocator.GPSHEIGHT,
		cellocator.NetworkTypeId,
		cellocator.InsertDate,
		cellocator.UTCTime,
		cellocator.DriverId,
		cellocator.TxReasonId,
		cellocator.AlertReason,
		cellocator.Hibernation,
		cellocator.HRNetwork,
		cellocator.MileCounter,
		cellocator.GPSMode1,
		cellocator.GPSMode2,
		cellocator.OutputA,
		cellocator.OutputB,
		cellocator.OutputC,
		cellocator.OutputD,
		cellocator.OptionalInput,
		cellocator.GPSCommStatus,
		cellocator.RawData,
		cellocator.PLMN,
		cellocator.SN,
		cellocator.MessageType,
		cellocator.MsgProtocol,
		cellocator.TripId,
		cellocator.ManeuverId,
		cellocator.ManeuverUsage,
		cellocator.AccidentBuffer,
		cellocator.ItemId
	FROM cellocator;
END;;
DELIMITER ;;

