  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="./admin">Admin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample04">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="./" target="_blank" >Home Público
            <span class="sr-only">(current)</span>
          </a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Opciones</a>
          <div class="dropdown-menu" aria-labelledby="dropdown04">
            <a class="dropdown-item" href="admin/categorias/categorias.php">Categorías</a>
            <!-- <a class="dropdown-item" href="admin/subcategorias/subcategorias.php">SubCategorías</a> -->
            <a class="dropdown-item" href="admin/marcas/marcas.php">Marcas</a>
            <a class="dropdown-item" href="admin/productos/productos.php">Proyectos</a>
            <a class="dropdown-item" href="admin/noticias/noticias.php">Noticias</a>
            <a class="dropdown-item" href="admin/usuarios/usuarios.php">Usuarios</a>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false"> <?php echo $_SESSION['USER']['nombre']  ?> </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="./admin">Home Admin</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" id="logout">

              Cerrar Sessión
            </a>

            <form id="formLogout"  style="display: none;">
              <input type="hidden" value="43378389-1111985-958478073">
            </form>
            <div class="dropdown-divider"></div>
          </div>
        </li>
      </ul>

    </div>
  </nav>
</header>

